contigs: ../Steno_phage_output_ASM/polished-contigs
customDatabaseDirectory: databases
flyeModel: --nano-hq
input: ../Steno_phages
medakaModel: r941_min_sup_g507
outdir: output
output: ../Steno_phage_output_ASM
phage: ../Steno_phage_output_ASM/polished-contigs
sequencing: longread
temp_dir: /tmp
