args:
  contigs: null
  db_dir: null
  host: null
  hq_contigs: null
  input: test/nanopore-subset
  log: example-nano/spae.log
  output: example-nano/
  profile: null
  sequencing: longread
  temp_dir: null
params:
  flye: --nano-hq
  medaka: r941_min_sup_g507
resources:
  bigjob:
    cpu: 32
    mem: 64000
    time: 480
  smalljob:
    cpu: 8
    mem: 16000
    time: 480
