site_name: spae
site_url: "https://github.com/linsalrob/spae"
site_author: Bhavya Papudeshi
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - shell
        - python
nav:
    - ABOUT:
      - Overview: index.md