resources:
  smalljob:
    cpu: 8
    mem: 16000
    time: 480
  bigjob:
    cpu: 32
    mem: 64000
    time: 480

trimnami:
  qc:
    subsample:
      --bases 100M

params:
  medaka: "r1041_e82_400bps_sup_v4.2.0" # the current default in medaka v1.8 and the most recent model
  flye: "--nano-hq"
  genomeSize: 44k