# config settings the user is allowed to tweak
args:
  input:
  output:
  sequencing:
  db_dir:
  profile:
  temp_dir:

resources:
  smalljob:
    cpu: 8
    mem: 16000
    time: 480
  bigjob:
    cpu: 32
    mem: 64000
    time: 480

params:
  medaka: "r941_min_sup_g507"
  flye: "--nano-hq"
  subsample: ""
  #to subsample, change the above flage to subsample: "--subsample"
  #adaptors: ""
  adaptors: "fastp"
  #genomeSize: 44k

 