# config settings the user is allowed to tweak
args:
  input:
  output:
  sequencing:
  contigs:
  hq_contigs:
  db_dir:
  profile:
  temp_dir:

resources:
  job:
    cpu: 8
    mem: 16000
    time: 480
  assemble:
    cpu: 16
    mem: 64000
    time: 480

params:
  medaka: "r941_min_sup_g507"
  flye: "--nano-hq"
